  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `delete_flag` INT(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
