package org.pplm.gadgets.coder.test.entity;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.delete_flag
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.updator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private Long updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.label
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.remark
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_date
     *
     * @return the value of project.create_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_date
     *
     * @param createDate the value for project.create_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.creator_id
     *
     * @return the value of project.creator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.creator_id
     *
     * @param creatorId the value for project.creator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.delete_flag
     *
     * @return the value of project.delete_flag
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.delete_flag
     *
     * @param deleteFlag the value for project.delete_flag
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_date
     *
     * @return the value of project.update_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_date
     *
     * @param updateDate the value for project.update_date
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.updator_id
     *
     * @return the value of project.updator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.updator_id
     *
     * @param updatorId the value for project.updator_id
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setUpdatorId(Long updatorId) {
        this.updatorId = updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.label
     *
     * @return the value of project.label
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.label
     *
     * @param label the value for project.label
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.remark
     *
     * @return the value of project.remark
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.remark
     *
     * @param remark the value for project.remark
     *
     * @mbg.generated Tue Dec 19 19:09:38 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}